# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f7dc18057273055a9fd12584125324a40cfe49e37391d2cc5be3c12868b6895c73e124cc8079b911141ec78f7a4540bf3a16049e8e71e0d1334779b3fbde36c

test:
  secret_key_base: f3aab1f91acc01872770347eab4ff521a4d1a5a67371e14554d16cea0678e388ca650ec79841f7aa3b42376e261f57b9745be5121e4373b188c5e0c562eafc14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
